// Code generated by ent, DO NOT EDIT.

package ent

import (
	"expense-tracker/ent/budget"
	"expense-tracker/ent/category"
	"expense-tracker/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Budget is the model entity for the Budget schema.
type Budget struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate time.Time `json:"end_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BudgetQuery when eager-loading is set.
	Edges           BudgetEdges `json:"edges"`
	budget_category *int
	budget_user     *int
	selectValues    sql.SelectValues
}

// BudgetEdges holds the relations/edges for other nodes in the graph.
type BudgetEdges struct {
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BudgetEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BudgetEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Budget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case budget.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case budget.FieldID:
			values[i] = new(sql.NullInt64)
		case budget.FieldStartDate, budget.FieldEndDate:
			values[i] = new(sql.NullTime)
		case budget.ForeignKeys[0]: // budget_category
			values[i] = new(sql.NullInt64)
		case budget.ForeignKeys[1]: // budget_user
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Budget fields.
func (_m *Budget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case budget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case budget.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case budget.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case budget.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = value.Time
			}
		case budget.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field budget_category", value)
			} else if value.Valid {
				_m.budget_category = new(int)
				*_m.budget_category = int(value.Int64)
			}
		case budget.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field budget_user", value)
			} else if value.Valid {
				_m.budget_user = new(int)
				*_m.budget_user = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Budget.
// This includes values selected through modifiers, order, etc.
func (_m *Budget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the Budget entity.
func (_m *Budget) QueryCategory() *CategoryQuery {
	return NewBudgetClient(_m.config).QueryCategory(_m)
}

// QueryUser queries the "user" edge of the Budget entity.
func (_m *Budget) QueryUser() *UserQuery {
	return NewBudgetClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Budget.
// Note that you need to call Budget.Unwrap() before calling this method if this Budget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Budget) Update() *BudgetUpdateOne {
	return NewBudgetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Budget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Budget) Unwrap() *Budget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Budget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Budget) String() string {
	var builder strings.Builder
	builder.WriteString("Budget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_date=")
	builder.WriteString(_m.EndDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Budgets is a parsable slice of Budget.
type Budgets []*Budget
