// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-tracker/ent/category"
	"expense-tracker/ent/expense"
	"expense-tracker/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseCreate is the builder for creating a Expense entity.
type ExpenseCreate struct {
	config
	mutation *ExpenseMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ExpenseCreate) SetTitle(v string) *ExpenseCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ExpenseCreate) SetAmount(v float64) *ExpenseCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *ExpenseCreate) SetDate(v time.Time) *ExpenseCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableDate(v *time.Time) *ExpenseCreate {
	if v != nil {
		_c.SetDate(*v)
	}
	return _c
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *ExpenseCreate) SetCategoryID(id int) *ExpenseCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_c *ExpenseCreate) SetNillableCategoryID(id *int) *ExpenseCreate {
	if id != nil {
		_c = _c.SetCategoryID(*id)
	}
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *ExpenseCreate) SetCategory(v *Category) *ExpenseCreate {
	return _c.SetCategoryID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ExpenseCreate) SetUserID(id int) *ExpenseCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *ExpenseCreate) SetNillableUserID(id *int) *ExpenseCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ExpenseCreate) SetUser(v *User) *ExpenseCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ExpenseMutation object of the builder.
func (_c *ExpenseCreate) Mutation() *ExpenseMutation {
	return _c.mutation
}

// Save creates the Expense in the database.
func (_c *ExpenseCreate) Save(ctx context.Context) (*Expense, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExpenseCreate) SaveX(ctx context.Context) *Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExpenseCreate) defaults() {
	if _, ok := _c.mutation.Date(); !ok {
		v := expense.DefaultDate()
		_c.mutation.SetDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExpenseCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Expense.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := expense.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Expense.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Expense.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := expense.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Expense.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Expense.date"`)}
	}
	return nil
}

func (_c *ExpenseCreate) sqlSave(ctx context.Context) (*Expense, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExpenseCreate) createSpec() (*Expense, *sqlgraph.CreateSpec) {
	var (
		_node = &Expense{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(expense.Table, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(expense.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(expense.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   expense.CategoryTable,
			Columns: []string{expense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.expense_category = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   expense.UserTable,
			Columns: []string{expense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.expense_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExpenseCreateBulk is the builder for creating many Expense entities in bulk.
type ExpenseCreateBulk struct {
	config
	err      error
	builders []*ExpenseCreate
}

// Save creates the Expense entities in the database.
func (_c *ExpenseCreateBulk) Save(ctx context.Context) ([]*Expense, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Expense, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExpenseCreateBulk) SaveX(ctx context.Context) []*Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
